# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PNdiagnose.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10PNdiagnose.proto\"!\n\x0b\x44iagRequest\x12\x12\n\nIdentifier\x18\x01 \x01(\t\"E\n\tDiagReply\x12\x19\n\x04type\x18\x01 \x01(\x0e\x32\x0b.dieaseType\x12\x0f\n\x07\x63\x61m_img\x18\x02 \x01(\t\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05*\'\n\ndieaseType\x12\n\n\x06Normal\x10\x00\x12\r\n\tParkinson\x10\x01\x32\x37\n\tDiagnoser\x12*\n\x0cGetDiagnosis\x12\x0c.DiagRequest\x1a\n.DiagReply\"\x00\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_DIEASETYPE = DESCRIPTOR.enum_types_by_name['dieaseType']
dieaseType = enum_type_wrapper.EnumTypeWrapper(_DIEASETYPE)
Normal = 0
Parkinson = 1


_DIAGREQUEST = DESCRIPTOR.message_types_by_name['DiagRequest']
_DIAGREPLY = DESCRIPTOR.message_types_by_name['DiagReply']
DiagRequest = _reflection.GeneratedProtocolMessageType('DiagRequest', (_message.Message,), {
  'DESCRIPTOR' : _DIAGREQUEST,
  '__module__' : 'PNdiagnose_pb2'
  # @@protoc_insertion_point(class_scope:DiagRequest)
  })
_sym_db.RegisterMessage(DiagRequest)

DiagReply = _reflection.GeneratedProtocolMessageType('DiagReply', (_message.Message,), {
  'DESCRIPTOR' : _DIAGREPLY,
  '__module__' : 'PNdiagnose_pb2'
  # @@protoc_insertion_point(class_scope:DiagReply)
  })
_sym_db.RegisterMessage(DiagReply)

_DIAGNOSER = DESCRIPTOR.services_by_name['Diagnoser']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _DIEASETYPE._serialized_start=126
  _DIEASETYPE._serialized_end=165
  _DIAGREQUEST._serialized_start=20
  _DIAGREQUEST._serialized_end=53
  _DIAGREPLY._serialized_start=55
  _DIAGREPLY._serialized_end=124
  _DIAGNOSER._serialized_start=167
  _DIAGNOSER._serialized_end=222
# @@protoc_insertion_point(module_scope)
